[package]
name = "kubos-app-service"
version = "0.1.0"
authors = ["Marshall Culpepper <marshall@kubos.com>"]
edition = "2018"

[dependencies]
kubos-app = { path = "../../apis/app-api/rust" }
kubos-service = { path = "../kubos-service" }

failure = "0.1.2"
fs_extra = "1.1.0"
getopts = "0.2"
juniper =  "0.15"
log = "^0.4.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
syslog = "4.0"
toml = "0.4"
uuid = { version = "0.6", features = ["v4"] }

[dev-dependencies]
kubos-system = { path = "../../apis/system-api" }
reqwest = "0.9.9"
serde_json = "1.0"
tempfile = "3"
warp = "0.1.12"
