[package]
name = "kubos-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
juniper = "0.15"
juniper_warp = "0.2.0"
kubos-system = { path = "../../apis/system-api" }
log = "^0.4.0"
warp = "0.1.12"

[dev-dependencies]
failure = "0.1.2"
